baseURL = "/"
languageCode = "en-us"
title = "GoMLX — Machine Learning for Go"
theme = "gomlx"
enableGitInfo = true
enableRobotsTXT = true

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
    guessSyntax = true
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "An easy-to-use ML and math framework for Go. No Python. Like PyTorch, Jax, or TensorFlow for Go."
  version = "v0.27.3"
  github = "https://github.com/gomlx/gomlx"
  slack = "https://app.slack.com/client/T029RQSE6/C08TX33BX6U"
  accent = "#0FA878"

[menu]
  [[menu.main]]
    name = "Get Started"
    url = "/docs/installation/"
    weight = 1
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2
  [[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 3
  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 4

[outputs]
  home = ["HTML", "RSS"]
